server.port=${PORT:8080}
spring.datasource.url=${DB_URLS}
spring.datasource.username=${DB_USERNAMES}
spring.datasource.password=${DB_PASSWORDS}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

amravati.app.jwtSecret=${AMRAVATI_APP_JWTSECRET}
